### PR TITLE
Added company you keep

### PR DESCRIPTION
**Pull request by quietlibrarian5**
mention for data nerd peeps

### CODE REVIEW

**Comment by quietlibrarian5** [comment]
@rrasins @kkousek  @josephinemorton @fionajones
Pleeeez take a look and comment!

**Review by kkousek — COMMENTED** [review]
How poetic.

**Comment by quietlibrarian5** [comment]
OMG!
I closed the Pull request before getting your comments!
@rrasins,  @josephinemorton @fionajones @leecri

**Comment by quietlibrarian5** [comment]
OMG!
I closed the Pull request before getting your comments!
@rrasins, @josephinemorton @fionajones @leecri

**Pull request merged**
